apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sre-demo-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: sre-demo-app
  namespaceSelector:
    matchNames:
      - sre-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
