version: '3.8'

services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw

      # Broker listener + internal KRaft controller listener
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

      # IMPORTANT:
      # Other Docker containers connect using kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      # Listener configuration
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Single-node development configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Topic defaults
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - eesp-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped

networks:
  eesp-network:
    name: eesp-network
    driver: bridge
    external: true
volumes:
  kafka-data:

