apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-consumer
  namespace: platform
  labels:
    app: event-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-consumer
  template:
    metadata:
      labels:
        app: event-consumer
    spec:
      containers:
        - name: event-consumer
          image: 760652872045.dkr.ecr.ap-south-1.amazonaws.com/eesp/event-consumer:1.0
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "events"
            - name: KAFKA_GROUP_ID
              value: "event-consumer-group"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
