apiVersion: v1
kind: Service
metadata:
  name: event-producer
  namespace: platform
  labels:
    app: event-producer
spec:
  type: ClusterIP
  selector:
    app: event-producer
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
